return {
  vim.loop.cwd(),
  -- runtime path
  vim.opt.runtimepath._info.default:match("/[^,]+runtime"),
  "~/dots",
  "~/.config/nvim",
  "~/.config/zsh",
  "~/.config/awesome",
  "~/Sources/nvim/neovim",
  "~/Sources/nvim/fzf-lua",
  "~/Sources/nvim/fzf-lua.wiki",
  "~/Sources/nvim/nvim-lua",
  "~/Sources/nvim/nvim-fzf",
  "~/Sources/nvim/nvim-dap",
  "~/Sources/nvim/vgit.nvim",
  "~/Sources/nvim/plenary.nvim",
  "~/Sources/nvim/telescope.nvim",
  "~/Sources/nvim/ts-vimdoc.nvim",
  "~/Sources/nvim/smartyank.nvim",
  "~/Sources/nvim/vim-cheatsheet",
  vim.fn.stdpath("data") .. "/site/pack/packer",
}
